import { CarouselItem, Achievement, Teacher, Course } from './types';

export const carouselItems: CarouselItem[] = [
  {
    id: 1,
    title: 'Môn Toán',
    description: 'Khóa học lập trình web toàn diện từ cơ bản đến nâng cao',
    image: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 2,
    title: 'Môn Vật Lý',
    description: 'Bắt đầu hành trình lập trình với Python - ngôn ngữ dễ học nhất',
    image: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  },
  {
    id: 3,
    title: 'Môn Hoá Học',
    description: 'Phát triển ứng dụng di động với React Native và Flutter',
    image: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
];

export const achievements: Achievement[] = [
  {
    icon: '🎓',
    title: '5 năm kinh nghiệm',
    description: 'Giảng dạy liên tục trong ngành Toán học',
  },
  {
    icon: '👥',
    title: '2000+ học viên',
    description: 'Đã giúp hàng nghìn học viên đạt được mục tiêu của mình',
  },
  {
    icon: '⭐',
    title: '4.9/5 đánh giá',
    description: 'Chất lượng giáo dục được học viên xác nhận',
  },
  {
    icon: '🏆',
    title: 'Sertified Instructors',
    description: 'Toàn bộ giáo viên có chứng chỉ quốc tế',
  },
];

export const teachers: Teacher[] = [
  {
    id: 1,
    name: 'Nguyễn Văn A',
    subject: 'Lập trình Python',
    achievements: ['PyCon Speaker', 'Đạt giải thưởng Python Innovation', 'Tác giả của 5 cuốn sách'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    description: 'Với 8 năm kinh nghiệm lập trình Python, Nguyễn Văn A đã giảng dạy cho hơn 500 học viên. Ông chuyên về web scraping, data analysis, và machine learning.',
    quote: 'Python không chỉ là ngôn ngữ lập trình, mà là cách để giải quyết các vấn đề thực tế một cách hiệu quả.',
    experience: '8 năm kinh nghiệm',
  },
  {
    id: 2,
    name: 'Trần Thị B',
    subject: 'Phát triển Web',
    achievements: ['React Expert', 'Tác giả của 3 cuốn sách lập trình', 'Hơn 50 dự án hoàn thành'],
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    description: 'Trần Thị B là một nhà phát triển web fullstack với chuyên môn trong React, Node.js và TypeScript. Cô đã làm việc cho các công ty công nghệ hàng đầu tại Silicon Valley.',
    quote: 'Lập trình web là nghệ thuật kết hợp sáng tạo với công nghệ để tạo ra những ứng dụng tuyệt vời.',
    experience: '6 năm kinh nghiệm',
  },
  {
    id: 3,
    name: 'Lê Minh C',
    subject: 'Database & Backend',
    achievements: ['Database Architect', 'Giải pháp cho 100+ công ty', 'AWS Certified Solutions Architect'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    description: 'Lê Minh C là một chuyên gia về database và backend development. Ông có kinh nghiệm thiết kế và tối ưu hóa hệ thống cho các công ty lớn với hàng triệu người dùng.',
    quote: 'Một database tốt là nền tảng của bất kỳ ứng dụng lớn nào. Tối ưu hóa là chìa khóa thành công.',
    experience: '10 năm kinh nghiệm',
  },
  {
    id: 4,
    name: 'Phạm Quốc D',
    subject: 'Mobile Development',
    achievements: ['10+ ứng dụng trên App Store', 'Google Developer Expert', 'Hơn 1 triệu người dùng'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    description: 'Phạm Quốc D là một developer mobile giàu kinh nghiệm với các ứng dụng thành công trên cả iOS và Android. Ông chuyên về React Native và Flutter.',
    quote: 'Mobile development không chỉ là viết code, mà là tạo ra các trải nghiệm người dùng tuyệt vời trên thiết bị di động.',
    experience: '7 năm kinh nghiệm',
  },
];

export const courses: Course[] = [
  {
    id: 1,
    name: 'Python Cơ Bản',
    level: 'Cơ bản',
    schedule: 'Thứ 2, 4, 6 - 19:00-21:00',
    class: 'Lớp 1',
    duration: '8 tuần',
    capacity: 25,
    subject: 'Python',
    classNumber: 1,
  },
  {
    id: 2,
    name: 'Python Trung bình',
    level: 'Trung bình',
    schedule: 'Thứ 2, 4, 6 - 17:00-19:00',
    class: 'Lớp 2',
    duration: '8 tuần',
    capacity: 22,
    subject: 'Python',
    classNumber: 2,
  },
  {
    id: 3,
    name: 'Python Nâng cao',
    level: 'Nâng cao',
    schedule: 'Thứ 3, 5 - 20:00-22:00',
    class: 'Lớp 3',
    duration: '10 tuần',
    capacity: 20,
    subject: 'Python',
    classNumber: 3,
  },
  {
    id: 4,
    name: 'HTML & CSS Cơ Bản',
    level: 'Cơ bản',
    schedule: 'Thứ 2, 4, 6 - 17:00-19:00',
    class: 'Lớp 1',
    duration: '6 tuần',
    capacity: 30,
    subject: 'Web Development',
    classNumber: 1,
  },
  {
    id: 5,
    name: 'JavaScript & React',
    level: 'Trung bình',
    schedule: 'Thứ 3, 5, 7 - 18:00-20:00',
    class: 'Lớp 2',
    duration: '12 tuần',
    capacity: 25,
    subject: 'Web Development',
    classNumber: 2,
  },
  {
    id: 6,
    name: 'Node.js & Backend',
    level: 'Nâng cao',
    schedule: 'Thứ 2, 5 - 20:00-22:00',
    class: 'Lớp 3',
    duration: '10 tuần',
    capacity: 15,
    subject: 'Web Development',
    classNumber: 3,
  },
  {
    id: 7,
    name: 'SQL Cơ Bản',
    level: 'Cơ bản',
    schedule: 'Thứ 3, 6 - 18:00-20:00',
    class: 'Lớp 1',
    duration: '6 tuần',
    capacity: 20,
    subject: 'Database',
    classNumber: 1,
  },
  {
    id: 8,
    name: 'Advanced Database Design',
    level: 'Nâng cao',
    schedule: 'Thứ 2, 5 - 20:00-22:00',
    class: 'Lớp 2',
    duration: '10 tuần',
    capacity: 15,
    subject: 'Database',
    classNumber: 2,
  },
  {
    id: 9,
    name: 'React Native Cơ Bản',
    level: 'Trung bình',
    schedule: 'Thứ 4, 6 - 19:00-21:00',
    class: 'Lớp 1',
    duration: '12 tuần',
    capacity: 20,
    subject: 'Mobile Development',
    classNumber: 1,
  },
  {
    id: 10,
    name: 'Flutter Development',
    level: 'Trung bình',
    schedule: 'Thứ 3, 5, 7 - 19:00-21:00',
    class: 'Lớp 2',
    duration: '12 tuần',
    capacity: 18,
    subject: 'Mobile Development',
    classNumber: 2,
  },
];
