import { CarouselItem, Achievement, Teacher, Course } from './types';

export const carouselItems: CarouselItem[] = [
  {
    id: 1,
    title: 'Môn Toán',
    description: 'Khóa học lập trình web toàn diện từ cơ bản đến nâng cao',
    image: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
];

export const achievements: Achievement[] = [
  {
    icon: '🎓',
    title: '20 năm kinh nghiệm',
    description: 'Giảng dạy trong ngành Toán học',
  },
];

export const courses: Course[] = [
  {
    id: 1,
    name: 'Toán 10',
    level: 'Cơ bản và Nâng cao',
    schedule: 'Thứ 5, 7 - 17:30-19:00',
    class: 'Lớp 10',
    duration: '1.5 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 10,
  },
  {
    id: 2,
    name: 'Toán 11',
    level: 'Cơ Bản và Nâng cao',
    schedule: 'Thứ 3, 6 - 17:30-19:00',
    class: 'Lớp 11',
    duration: '1.5 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 11,
  },
  {
    id: 3,
    name: 'Toán 12A',
    level: 'Mới học bài 1 chương 1',
    schedule: 'Thứ 5 - 14:00-17:00',
    class: 'Lớp 12',
    duration: '3 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 12,
  },
  {
    id: 4,
    name: 'Toán 12B',
    level: 'Học hết bài 3 chương 1',
    schedule: 'Thứ 3, 6 - 15:00-17:00',
    class: 'Lớp 12',
    duration: '2 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 12,
  },
  {
    id: 5,
    name: 'Toán 12C',
    level: 'Đã học hết chương 1',
    schedule: 'Thứ 2, 4 - 19:30-21:00',
    class: 'Lớp 12',
    duration: '1.5 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 12,
  },
  {
    id: 7,
    name: 'Toán 7',
    level: 'Đã học hết bài 12 chương 1',
    schedule: 'Thứ 3, 4 - 16:00-17:30',
    class: 'Lớp 7',
    duration: '1.5 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 7,
  },
  {
    id: 8,
    name: 'Toán 8',
    level: 'Đã học hết bài 1 chương 1',
    schedule: 'Thứ 2, 4 - 19:30-21:00',
    class: 'Lớp 8',
    duration: '1.5 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 8,
  },
  {
    id: 9,
    name: 'Toán 9',
    level: 'Đã học hết bài 2 chương 1',
    schedule: 'Thứ 2, 4 - 15:00-17:00',
    class: 'Lớp 9',
    duration: '2 giờ/buổi',
    capacity: 10,
    subject: 'Toán',
    classNumber: 9,
  },
  {
    id: 10,
    name: 'Vật lý 10',
    level: 'Cơ bản và Nâng cao',
    schedule: '',
    class: 'Lớp 10',
    duration: '',
    capacity: 10,
    subject: 'Vật lý',
    classNumber: 10,
  },
  {
    id: 11,
    name: 'Vật lý 11',
    level: 'Cơ bản và Nâng cao',
    schedule: '',
    class: 'Lớp 11',
    duration: '',
    capacity: 10,
    subject: 'Vật lý',
    classNumber: 11,
  },
  {
    id: 12,
    name: 'Vật lý 12',
    level: 'Cơ bản và Nâng cao',
    schedule: '',
    class: 'Lớp 12',
    duration: '',
    capacity: 10,
    subject: 'Vật lý',
    classNumber: 12,
  },
];

export const teachers: Teacher[] = [
  {
    id: 1,
    name: 'Nguyễn Thị Thu Hằng',
    subject: 'Dạy Toán',
    achievements: ['Thạc sĩ chuyên ngành phương pháp Toán sơ cấp', 'Thành viên hội toán học Hà Nội', 'Giáo viên toán THPT Lê Quý Đôn-Đống Đa'],
    image: 'https://i.ibb.co/NgdbcF9m/Chat-GPT-Image-May-16-2026-10-37-02-PM.png',
    description: 'Với 25 năm kinh nghiệm giảng dạy Toán học, luyện ôn thi THPT và bồi dưỡng học sinh giỏi ôn thi Olympic, cô Hằng đã có các chuyên đề báo cáo ở các hội thảo toán học về chương trình đổi mới của Bộ Giáo Dục.',
    quote: 'Toán học không chỉ là con số, mà là cách để giải quyết các vấn đề thực tế một cách hiệu quả.',
    experience: '25 năm kinh nghiệm',
    courses: courses.filter((course) => course.id >= 1 && course.id <= 5),
  },
  {
    id: 2,
    name: 'Nguyễn Văn Hiếu',
    subject: 'Dạy Lý',
    achievements: ['Thạc sĩ môn Vật lý', 'Giáo viên Vật lý THPT Lê Quý Đôn-Đống Đa', 'Chuyên ôn tuyển HSG'],
    image: 'https://res.cloudinary.com/dnlbkamkg/image/upload/f_auto,q_auto/2aOboQea6E99o7PXST6ujCFsFhklnD7HVWdelF8i_wbe8tr.png',
    description: 'Giáo viên THPT Lê Quý Đôn-Đống Đa, chuyên dạy môn Vật lý, có nhiều năm kinh nghiệm trong việc giảng dạy và bồi dưỡng học sinh giỏi.',
    quote: 'Vật lý là chìa khóa để hiểu và khám phá thế giới xung quanh chúng ta, từ những hiện tượng tự nhiên đến các ứng dụng công nghệ tiên tiến.',
    experience: 'Hơn 25 năm kinh nghiệm',
    courses: courses.filter((course) => course.id >= 10),
  },
];
